name: Update File

on:
  schedule:
    - cron: '55 * * * *' # 每天 UTC 时间 00:00 运行

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # 检出仓库代码
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run script
      run: python action.py # 执行你的脚本
    - name: Commit and push if changed
      run: |
        git config --global user.email "hexdcode@proton.me"
        git config --global user.name "hexdcode"
        git add -A
        git commit -m "Updated file" -a || echo "No changes to commit"
        git push
